name: develop

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Databricks Repos Pull (PROD)
        run: |
          curl -X POST "${{ secrets.DATABRICKS_HOST }}/api/2.0/repos/${{ secrets.DATABRICKS_PROD_REPO_ID }}/pull" \
                -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d '{"branch": "main"}'
